# Generated by Django 2.1.4 on 2019-01-28 07:34

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConstUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('user_id', models.IntegerField()),
                ('dob', models.CharField(max_length=50)),
                ('verified_level', models.IntegerField(default=0)),
                ('constant_balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('constant_balance_holding', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'managed': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('overdue', 'Overdue')], default='active', max_length=50)),
            ],
            options={
                'verbose_name': 'Loan',
                'verbose_name_plural': 'Loans',
            },
        ),
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('member_required', models.IntegerField(help_text='How many members required to apply to this loan')),
                ('member_allowed', models.IntegerField(help_text='How many members allowed to loan')),
                ('rate', models.DecimalField(decimal_places=2, help_text='Loan rate', max_digits=8)),
                ('cycle', models.IntegerField(help_text='How many days need to pay the loan. For example 7 days')),
                ('term', models.IntegerField(help_text='How many cycle need to pay the loan. For example 12 cycles')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('approved', 'Approved')], default='pending', max_length=50)),
            ],
            options={
                'verbose_name': 'Loan Application',
                'verbose_name_plural': 'Loan Applications',
            },
        ),
        migrations.CreateModel(
            name='LoanMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('user_email', models.CharField(max_length=255)),
                ('user_external_email', models.CharField(max_length=255, null=True)),
                ('credit', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Loan Member',
                'verbose_name_plural': 'Loan Members',
            },
        ),
        migrations.CreateModel(
            name='LoanMemberApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loan_member_applications', to='loan.LoanApplication')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loan_member_members', to='loan.LoanMember')),
            ],
            options={
                'verbose_name': 'Loan Member In Application',
                'verbose_name_plural': 'Loan Members In Applications',
            },
        ),
        migrations.CreateModel(
            name='LoanMemberApplicationDataField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('field_value', models.CharField(max_length=500)),
                ('field_type', models.CharField(choices=[('number', 'Number'), ('text', 'Text'), ('image', 'Image'), ('file', 'File')], default='text', max_length=50)),
                ('loan_applicant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applicant_data_fields', to='loan.LoanMemberApplication')),
            ],
        ),
        migrations.CreateModel(
            name='LoanPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('original_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('interest_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fee', models.DecimalField(decimal_places=2, max_digits=12)),
                ('loan_applicant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applicant_payments', to='loan.LoanMemberApplication')),
            ],
            options={
                'verbose_name': 'Loan Payment',
                'verbose_name_plural': 'Loan Payments',
            },
        ),
        migrations.CreateModel(
            name='LoanProgram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('min_loan_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('max_loan_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('min_member', models.IntegerField()),
                ('max_member', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cycle', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Loan Program',
                'verbose_name_plural': 'Loan Programs',
            },
        ),
        migrations.CreateModel(
            name='LoanTerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('original_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('interest_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('pay_date', models.DateTimeField(help_text='The date member should pay the loan')),
                ('paid_date', models.DateTimeField(help_text='The date member paid the loan')),
                ('paid_status', models.CharField(choices=[('early_paid', 'Early Paid'), ('paid', 'Paid'), ('late', 'Late'), ('late_paid', 'Late Paid')], max_length=50, null=True)),
                ('paid', models.BooleanField(default=False)),
                ('loan_applicant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applicant_terms', to='loan.LoanMemberApplication')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loan_payment_terms', to='loan.LoanPayment')),
            ],
            options={
                'verbose_name': 'Loan Term',
                'verbose_name_plural': 'Loan Terms',
            },
        ),
        migrations.CreateModel(
            name='MemberCreditHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('point', models.IntegerField()),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_histories', to='loan.LoanMember')),
            ],
            options={
                'verbose_name': 'Member Credit History',
                'verbose_name_plural': 'Member Credit Histories',
            },
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_applications', to='loan.LoanProgram'),
        ),
        migrations.AddField(
            model_name='loan',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='application_loans', to='loan.LoanApplication'),
        ),
        migrations.AddField(
            model_name='loan',
            name='loan_applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applicant_loans', to='loan.LoanMemberApplication'),
        ),
    ]
