# Generated by Django 2.1.4 on 2019-01-28 10:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanmember',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loanmember',
            name='phone_retry',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='loanmember',
            name='phone_verification_code',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='loanmember',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='loanmember',
            name='user_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='loanmemberapplication',
            name='main',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanmemberapplication',
            name='status',
            field=models.CharField(choices=[('connecting', 'Connecting'), ('connected', 'Connected')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='member_allowed',
            field=models.IntegerField(help_text='How many members allowed to loan per cycle'),
        ),
        migrations.AlterField(
            model_name='loanmember',
            name='user_external_email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='loanmember',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loanmemberapplication',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
