# Generated by Django 2.1.4 on 2019-01-28 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0003_auto_20190128_1021'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanApplicationBusiness',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('loan.loanapplication',),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=50),
        ),
    ]
