# Generated by Django 2.1.4 on 2019-01-29 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0004_auto_20190128_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='members',
            field=models.ManyToManyField(related_name='applications_of_member', through='loan.LoanMemberApplication', to='loan.LoanMember'),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('pending', 'Pending'), ('processing', 'Processing'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='created', max_length=50),
        ),
    ]
