# Generated by Django 2.1.4 on 2019-01-29 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0006_auto_20190129_0700'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanMemberBusiness',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('loan.loanmember',),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loanprogram',
            name='max_term',
            field=models.IntegerField(default=12),
        ),
    ]
