# Generated by Django 2.1.4 on 2019-01-30 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0007_auto_20190129_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanterm',
            name='notification_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanterm',
            name='notification_status',
            field=models.CharField(choices=[('not_yet', 'Not Yet'), ('called', 'Called'), ('email_sent', 'Email Sent')], default='not_yet', max_length=50),
        ),
    ]
