# Generated by Django 2.1.4 on 2019-01-30 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0008_auto_20190130_0332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanterm',
            name='paid_date',
            field=models.DateTimeField(help_text='The date member paid the loan', null=True),
        ),
        migrations.AlterField(
            model_name='loanterm',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='loan_payment_terms', to='loan.LoanPayment'),
        ),
    ]
