# Generated by Django 2.1.4 on 2019-01-30 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0009_auto_20190130_0338'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanTermNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notification_status', models.CharField(choices=[('not_yet', 'Not Yet'), ('called', 'Called'), ('email_sent', 'Email Sent')], default='not_yet', max_length=50)),
                ('notification_note', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='loanterm',
            name='notification_note',
        ),
        migrations.RemoveField(
            model_name='loanterm',
            name='notification_status',
        ),
    ]
